%YAML 1.2
---
language: python
python:
  - 2.7
  - pypy
  - 3.3
  - 3.4
install:
  - pip install -e .
  - pip install -r test-requirements.txt
script: nosetests
after_success:
  - coveralls

# deploy:
#   provider: pypi
#   user: djt5019
#   distributions: "sdist bdist_wheel"
#   on:
#     python: 2.7
#     tags: true
#     all_branches: true
#   password:
#     secure: [replace]
